# Generated by Django 4.2.13 on 2024-06-26 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('New_App', '0003_rename_prodect_code_mytable_product_code_and_more'),
        ('Ordermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_since',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, null=True)),
                ('order_date', models.DateField(null=True)),
                ('quantity', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('gst_amount', models.FloatField(default=0)),
                ('bill_amount', models.FloatField(default=0)),
                ('Customer_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ordermanagement.customer')),
                ('product_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='New_App.mytable')),
            ],
        ),
    ]
