# Generated by Django 4.2.13 on 2024-06-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='food_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mytable',
            name='gst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
